// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASi4zEFQfaKrtmZAVH4vwxOgz9-x5dr9k',
    appId: '1:891599911054:web:5680b6c105bff58a3431df',
    messagingSenderId: '891599911054',
    projectId: 'whatsapp-backend-74eb6',
    authDomain: 'whatsapp-backend-74eb6.firebaseapp.com',
    storageBucket: 'whatsapp-backend-74eb6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHNF-g6MyH6mhUNPEJsy5yW87CnTUSRMs',
    appId: '1:891599911054:android:25d27f64f49d83143431df',
    messagingSenderId: '891599911054',
    projectId: 'whatsapp-backend-74eb6',
    storageBucket: 'whatsapp-backend-74eb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz79_Nwd7q0hl_ZYc36cImuXsMpGoISao',
    appId: '1:891599911054:ios:9a8f5a4d82061de03431df',
    messagingSenderId: '891599911054',
    projectId: 'whatsapp-backend-74eb6',
    storageBucket: 'whatsapp-backend-74eb6.appspot.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
